package com.mycompany.myapp.Coupon.magasin;

import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

import com.codename1.ui.Toolbar;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current, hi;
    private Resources theme;

    public MyApplication() {
        this.start();
    }



    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }

    public void start() {
//        MagasinList magasinList = new MagasinList(theme);
//        magasinList.getF().show();
//        ListProduit magasinList = new ListProduit(theme);
//        magasinList.getF().show();

        HomeMagasin home = new HomeMagasin();
        home.getF().show();
//            SwippableTab s = new SwippableTab(theme);
//            s.getF().show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }

    public void destroy() {
    }

    public Form getF() {

        return hi;
    }

}
