package com.mycompany.myapp.produit;

import Entities.Produit;
import com.codename1.components.ImageViewer;
import com.codename1.io.ConnectionRequest;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.NetworkEvent;
import com.codename1.io.NetworkManager;
import com.codename1.ui.Button;
import com.codename1.ui.Container;
import com.codename1.ui.Display;
import com.codename1.ui.EncodedImage;
import com.codename1.ui.FontImage;
import com.codename1.ui.Graphics;
import com.codename1.ui.Image;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.URLImage;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.list.DefaultListModel;
import com.mycompany.myapp.Coupon.MainCoupon;
import java.io.IOException;
import java.util.ArrayList;
import service.ProduitService;
import service.ToolbarSideMenu;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class Home {

    private Resources theme;
    
    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        Toolbar.setGlobalToolbar(true);
        Toolbar.setCenteredDefault(false);
    }

    public void start() {

        Form hi = new Form();
        Image maskedImage = null;
        try {

            Image profilePic = Image.createImage("/lana.jpg");
            //form.addComponent(label1);
            int w = profilePic.getWidth();
            int h = profilePic.getHeight();
            Image maskImage = Image.createImage(w, h);
            Graphics g = maskImage.getGraphics();
            g.setAntiAliased(true);
            g.setColor(0x000000);
            g.fillRect(0, 0, w, h);
            g.setColor(0xffffff);
            g.fillArc(0, 0, w, h, 0, 360);

            Object mask = maskImage.createMask();

            maskedImage = profilePic.applyMask(mask);

        } catch (IOException ex) {
        }

        hi.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
        TextField txtSearch = new TextField();
        Container cont = new Container(new BoxLayout(BoxLayout.X_AXIS));

        hi.getToolbar();
        txtSearch.setHint("Search Produit");

        hi.getToolbar().addMaterialCommandToRightBar("", FontImage.MATERIAL_SEARCH, e -> {
            new Search().start(txtSearch.getText());

        });
        hi.getToolbar().addCommandToRightBar("", maskedImage.scaled(50, 50), e -> {
        });

        cont.add(txtSearch);

        cont.setScrollableX(false);
        cont.setScrollableY(false);
        hi.add(cont);
        
        Container container1 = new Container();
        Button b = new Button();
        b.addActionListener(e->{new MainCoupon().start();
});
        container1.add(new Label("Tous Les Coupons"));
        container1.setLeadComponent(b);
        hi.add(container1);
        
        
        
        
        
        DefaultListModel listeImageCoupon= new DefaultListModel<>();
        try {
            Image imagecoupon1 = Image.createImage("/coupon1.jpg");
            Image imagecoupon2 = Image.createImage("/coupon2.png");
            Image imagecoupon3 = Image.createImage("/coupon3.jpg");
            listeImageCoupon.addItem(imagecoupon1.scaled(Display.getInstance().getDisplayWidth(),Display.getInstance().getDisplayHeight()/2));
            listeImageCoupon.addItem(imagecoupon2.scaled(Display.getInstance().getDisplayWidth(),Display.getInstance().getDisplayHeight()/2));
            listeImageCoupon.addItem(imagecoupon3.scaled(Display.getInstance().getDisplayWidth(),Display.getInstance().getDisplayHeight()/2));
            ImageViewer imgvCoupon = new ImageViewer();
            imgvCoupon.setImageList(listeImageCoupon);
            imgvCoupon.animate();
            hi.add(imgvCoupon);
        } catch (IOException ex) {
        }
        System.out.println("");
        //Button group
        new ToolbarSideMenu().insertSetting(hi, false);
        hi.show();
        //Lister categorie
        ConnectionRequest con = new ConnectionRequest();
        con.setUrl("http://localhost/pidev2017/produit/select.php");
        con.addResponseListener(new ActionListener<NetworkEvent>() {
            Container LesProduits = new Container(new BoxLayout(BoxLayout.X_AXIS));

            @Override
            public void actionPerformed(NetworkEvent evt) {

                Label LesNouveauxProduits = new Label("Les Nouveaux Produits");
                Container a = new Container();
                a.add(LesNouveauxProduits);
                Button btnLesNouveauxProduits = new Button();
                btnLesNouveauxProduits.addActionListener(e -> {
                    System.out.println("sss");
                });
                a.add(btnLesNouveauxProduits);
                a.setLeadComponent(btnLesNouveauxProduits);
                btnLesNouveauxProduits.setHidden(true);
                hi.add(a);
                LesProduits.setScrollableX(true);
                LesProduits.setScrollableY(false);
                ArrayList<Produit> produits = new ProduitService().getListProduits(new String(con.getResponseData()));
                for (Produit produit : produits) {
                    System.out.println(produit.getCreatedDate());
                    try {

                        Container containerProduit = new Container(new BoxLayout(BoxLayout.Y_AXIS));
                        EncodedImage placeholder = EncodedImage.createFromImage(Image.createImage("/error.jpg"), false);
                        Image image = URLImage.createToStorage(placeholder, "magasin+" + "/" + produit.getImageName(), "http://localhost/pidev2017/image/" + "/" + produit.getImageName());
                        containerProduit.add(image.scaled(100, 100));
                        Container detailsContainer = new Container(new BoxLayout(BoxLayout.Y_AXIS));
                        detailsContainer.add(new Label(produit.getLibelle()));
                        detailsContainer.add(produit.getPrixProduit().toString());
                        containerProduit.add(detailsContainer);
                        Button b = new Button(produit.getLibelle());
                        b.addActionListener(e -> {
                            new AfficherProduit().start(produit.getId(), false);
                        });
                        b.setHidden(true);
                        containerProduit.add(b);
                        containerProduit.setLeadComponent(b);
                        LesProduits.add(containerProduit);

                    } catch (IOException ex) {
                    }

                }

                hi.add(LesProduits);
                hi.refreshTheme();
            }
        });
        NetworkManager.getInstance().addToQueue(con);

    }

    public void destroy() {
    }

}
//                    int Day = 24 * 60 * 60 * 1000;
//                    Date d = new Date();
//                    double daydifference = Math.abs(produit.getCreatedDate().getTime() - d.getTime()) / Day;
//                    if (daydifference < Day * 7) {
