package com.mycompany.myapp.produit;

import Entities.Categorie;
import Entities.Produit;
import com.codename1.io.ConnectionRequest;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.NetworkEvent;
import com.codename1.io.NetworkManager;
import com.codename1.ui.Button;
import com.codename1.ui.Container;
import com.codename1.ui.EncodedImage;
import com.codename1.ui.Image;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.URLImage;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BoxLayout;
import java.io.IOException;
import java.util.ArrayList;
import service.ProduitService;
import service.ToolbarSideMenu;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class ListProduit {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        Toolbar.setGlobalToolbar(true);
        Toolbar.setCenteredDefault(false);
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }

        com.codename1.ui.util.Resources resourceObjectInstance;
        Form hi = new Form();
        hi.setLayout(new BoxLayout(BoxLayout.Y_AXIS));

        TextField txtSearch = new TextField();
        Container cont = new Container(new BoxLayout(BoxLayout.X_AXIS));
        Button btnSearch = new Button("search");
        txtSearch.setHint("Search Produit");
        cont.add(btnSearch);
        btnSearch.addActionListener(e -> {
            new Search().start(txtSearch.getText());
        });
        cont.add(txtSearch);
        cont.setScrollableX(false);
        cont.setScrollableY(false);
        hi.add(cont);
        hi.add(new Label("Les Produits"));
        
        //Button group
        
        
        new ToolbarSideMenu().insertSetting(hi,false);
        hi.show();
        //Lister categorie
        ConnectionRequest con = new ConnectionRequest();
        con.setUrl("http://localhost/pidev2017/produit/select.php");
        ArrayList<Categorie> categorie2;
        con.addResponseListener(new ActionListener<NetworkEvent>() {
            Container LesProduits = new Container(new BoxLayout(BoxLayout.X_AXIS));

            @Override
            public void actionPerformed(NetworkEvent evt) {

                LesProduits.setScrollableX(true);
                LesProduits.setScrollableY(false);
                ArrayList<Produit> produits = new ProduitService().getListProduits(new String(con.getResponseData()));
                int size = produits.size();
               
                for (Produit produit : produits) {

                    try {
                        Container containerProduit = new Container(new BoxLayout(BoxLayout.Y_AXIS));
                        EncodedImage placeholder = EncodedImage.createFromImage(Image.createImage("/error.jpg"), false);
                        Image image = URLImage.createToStorage(placeholder, produit.getImageName(), "http://localhost/pidev2017/image/" + "/" + produit.getImageName());
                        containerProduit.add(image.scaled(100, 100));
                        Container detailsContainer = new Container(new BoxLayout(BoxLayout.Y_AXIS));
                        detailsContainer.add(new Label(produit.getLibelle()));
                        detailsContainer.add(produit.getPrixProduit().toString());
                        containerProduit.add(detailsContainer);
                        Button b = new Button(produit.getLibelle());
                        b.addActionListener(e -> {
                            new AfficherProduit().start(produit.getId(), false);
                        });
                        b.setHidden(true);
                        containerProduit.add(b);
                        containerProduit.setLeadComponent(b);
                        LesProduits.add(containerProduit);

                    } catch (IOException ex) {
                        System.out.println(new String(con.getResponseData()));
                    }
                }
                hi.add(LesProduits);
                hi.refreshTheme();
            }
        });
        NetworkManager.getInstance().addToQueue(con);

    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }

    public void destroy() {
    }

}
